### ISSUE TITLE
Ros launch file missing for your ROS node

### ISSUE THREAD

**Issue by TCIII** [wennycooper/Auto-Docking-Design#1]
@wennycooper,

We are in the process of using your docking station software in a project involving an [ArloBot](https://github.com/chrisl8/ArloBot). 

I updated your IR Transmitter and Receiver Arduino code to improve its response speed.

I am not a ROS programmer by any means so I am wondering if you ever created a ROS launch file for your `mybot_autodocking mybot_autodocking_irCode` that specifies the Arduino IR Receiver USB port and any other support modules (rosserial_py) that are required?

Regards,
TCIII

**Comment by wennycooper** [comment]
You need to specify Arduino IR Receiver USB port in rosserial_python. 
Something like:

    $ rosrun rosserial_python serial_node.py _port:=/dev/ttyACM1 _baud:=57600

Please refer to:
http://wiki.ros.org/rosserial_python

We don't need to specify USB port number in mybot_autodocking or mybot_autodocking_irCode, they are communicate via ROS topic to Arduino.

Hope this helps.

**Comment by TCIII** [comment]
@wennycooper,

Thanks for the response, much appreciated.

Without a launch file we have been using this sequence of commands to view /irCode:

`source ~/catkin_ws/devel/setup.bash`
`rosrun mybot_autodocking mybot_autodocking_irCode`

`source ~/catkin_ws/devel/setup.bash`
`rosrun rosserial_python serial_node.py /dev/ttyUSB0`

`source ~/catkin_ws/devel/setup.bash`
`rostopic echo /irCode`

When I had the IR beam illuminating both IR Receivers the output looked like this:

x: 1.0
y: 1.0
z: 0.0

When I had the IR beam illuminating the Right IR Receiver the output looked like this:

x: 0.0
y: 1.0
z: 0.0

When I had the IR beam illuminating the Left IR Receiver the output looked like this:

x: 1.0
y: 0.0
z: 0.0

When I had the IR beam illuminating both IR Receivers both wheels were turning backwards as the robot thinks it is now aligned to the dock and is trying to engage the dock. The wheels are turning backwards because your mybot_autodocking_irCode had the robot back into the dock.

Does this look correct?

TCIII

**Comment by wennycooper** [comment]
Yes, it looks correct. Congratulations! :)

**Comment by TCIII** [comment]
@wennycooper,

Thanks for the response, much appreciated.

I will close this issue.

TCIII
